version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm ci
      - echo Running vulnerability check...
      # - npm audit
      - echo Building application...
      # - npm run build
      - echo Running tests...
      # - npm test   
      - echo Retrieving ECR repository URL from Parameter Store...
      - export ECR_REPO_URL=$(aws ssm get-parameter --name "/app/ecr_repo_url" --query "Parameter.Value" --output text)
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ${ECR_REPO_URL}
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t app-image .
      - docker tag app-image:latest ${ECR_REPO_URL}:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push ${ECR_REPO_URL}:latest
      - echo Writing definition file ...
      - printf '[{"name":"nodejs_ecs_first_task","imageUri":"%s"}]' ${ECR_REPO_URL}:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
